# -*- coding: utf-8 -*-
"""
LoRA Librarian
==============
AI model (Checkpoint / LoRA) kütüphanenizi otomatik olarak düzenleyen,
eksik kapak/etiket verisini Civitai'den tamamlayan ve düşük puanlı ya
da eski sürümleri ayıklayan modern, çift dilli masaüstü uygulaması.

A modern, bilingual desktop app that automatically organizes your AI
model (Checkpoint / LoRA) library, fills in missing cover/tag data
from Civitai, and separates out low-rated or outdated versions.

License: MIT
"""

import os
import re
import sys
import html
import hashlib
import shutil
import time
import json
import threading

import requests
import customtkinter as ctk
import tkinter as tk
from tkinter import filedialog, messagebox

from lang import t
from base_models import normalize_base_model

APP_VERSION = "2.0.0"
API_DOMAIN = "civitai.red"

# By default Civitai's API only returns SFW sample images for a model
# version - an NSFW-flagged model's "images" array comes back empty
# unless the request explicitly asks for mature content. This is why
# trigger-word extraction from sample images was silently failing for
# NSFW LoRAs. browsingLevel=31 is the bitmask for "show every content
# level" (1 PG + 2 PG13 + 4 R + 8 X + 16 XXX); nsfw=true is the older
# equivalent, sent alongside for endpoints that only recognize it.
CIVITAI_CONTENT_PARAMS = {"nsfw": "true", "browsingLevel": 31}

# Native display names shown on the language switcher - shown in each
# language's own script so they're recognizable regardless of which
# language the UI is currently in.
LANG_CODES = ["tr", "en", "ja", "zh"]
LANG_LABELS = {"tr": "Türkçe", "en": "English", "ja": "日本語", "zh": "中文"}

CONFLICT_CODES = ["rename", "skip", "overwrite"]
CONFLICT_KEYS = {"rename": "conflict_rename", "skip": "conflict_skip", "overwrite": "conflict_overwrite"}

CREATOR_CODES = ["off", "all", "list"]
CREATOR_KEYS = {"off": "creator_mode_off", "all": "creator_mode_all", "list": "creator_mode_list"}

RENAME_MODE_CODES = ["meaningless", "all"]
RENAME_MODE_KEYS = {"meaningless": "rename_mode_meaningless", "all": "rename_mode_all"}

# Filenames that look like a hash / auto-generated ID rather than an
# actual model title - candidates for renaming when "meaningless only"
# mode is selected.
_MEANINGLESS_PATTERNS = [
    re.compile(r"^[0-9a-fA-F]{6,}$"),                       # hex hash
    re.compile(r"^-?\d+$"),                                  # pure number (with optional leading dash, e.g. "-000013")
    re.compile(r"(?i)^(lora|model|checkpoint|download|file|untitled|new\s*folder)[\s_-]*\d*$"),
    # UUID, optionally followed by a training-tool suffix like ".TA_trained"
    re.compile(r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}(\..*)?$"),
    # ULID / long random alphanumeric IDs generated by AI platforms
    # (Civitai on-site generator, PixAI, SeaArt, etc.) - long, no spaces,
    # mixes uppercase letters and digits with no lowercase letters.
    re.compile(r"^[A-Z0-9]{20,32}$"),
]

# CJK Unicode ranges (Hiragana/Katakana, CJK Unified Ideographs, etc.) -
# used to flag filenames that are entirely (or almost entirely)
# Japanese/Chinese, which should be renamed to the model's English
# Civitai title even in "meaningless only" mode.
_CJK_PATTERN = re.compile(r"[\u3040-\u30ff\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]")


def is_meaningless_name(name: str) -> bool:
    name = name.strip()
    if any(p.match(name) for p in _MEANINGLESS_PATTERNS):
        return True
    # A name made up mostly of CJK characters isn't "meaningless" in the
    # hash sense, but it isn't the English title either - the user wants
    # these translated too.
    if _CJK_PATTERN.search(name) and not re.search(r"[A-Za-z]{3,}", name):
        return True
    return False

# Theme-aware color tuples: (light_mode, dark_mode) - a dark violet /
# near-black palette with a purple-to-pink accent, plus a matching
# light-mode equivalent.
BG_MAIN = ("#f4f2fa", "#0e0d15")
BG_HEADER = ("#ffffff", "#131220")
CARD_BG = ("#ffffff", "#17161f")
SIDEBAR_BG = ("#ede9f7", "#121120")
SIDEBAR_ITEM_HOVER = ("#e0d9f5", "#1e1c2c")
SIDEBAR_TEXT = ("#3a3650", "#c9c6d9")
BORDER = ("#e2ddf0", "#2a2838")
LOG_BG = ("#efecf8", "#100f18")
TEXT_MUTED = ("#6b6880", "#9c99ab")

ACCENT = "#8b5cf6"       # violet - sidebar selection, focus highlights
ACCENT_HOVER = "#7c4ee8"
GRADIENT_STOPS = ["#4f46e5", "#9333ea", "#ec4899"]  # indigo -> violet -> pink

CORNER_BTN = 10
CORNER_CARD = 14
CORNER_INPUT = 8


def _hex_to_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def _rgb_to_hex(rgb):
    return "#%02x%02x%02x" % rgb


def _interp_color(stops, t_frac):
    """Interpolate a color along a multi-stop gradient (t_frac in [0,1])."""
    n = len(stops) - 1
    seg = min(int(t_frac * n), n - 1)
    local_t = (t_frac * n) - seg
    c1, c2 = _hex_to_rgb(stops[seg]), _hex_to_rgb(stops[seg + 1])
    mixed = tuple(int(c1[i] + (c2[i] - c1[i]) * local_t) for i in range(3))
    return _rgb_to_hex(mixed)


def draw_gradient_bar(canvas, width, height, stops=None):
    """Paint a thin horizontal gradient strip on a tk.Canvas - the
    purple-to-pink accent line seen along the top edge of the app."""
    stops = stops or GRADIENT_STOPS
    canvas.delete("all")
    steps = max(1, width // 2)
    for i in range(steps):
        frac = i / max(1, steps - 1)
        color = _interp_color(stops, frac)
        x = int(i * width / steps)
        x2 = int((i + 1) * width / steps) + 1
        canvas.create_rectangle(x, 0, x2, height, fill=color, outline=color)


def app_dir():
    if getattr(sys, "frozen", False):
        return os.path.dirname(sys.executable)
    return os.path.dirname(os.path.abspath(__file__))


SETTINGS_PATH = os.path.join(app_dir(), "ayarlar.json")
HASH_CACHE_PATH = os.path.join(app_dir(), "hash_cache.json")


class LoraLibrarianApp(ctk.CTk):
    def __init__(self):
        super().__init__()

        self.lang = "tr"
        self.islem_devam_ediyor = False
        self.hash_cache = self._hash_cache_yukle()
        self.session = requests.Session()

        self.api_key = ctk.StringVar()

        # --- CHECKPOINT ---
        self.cp_kaynak = ctk.StringVar()
        self.cp_chk_taban = ctk.BooleanVar(value=True)
        self.cp_chk_kategori = ctk.BooleanVar(value=False)
        self.cp_chk_resim = ctk.BooleanVar(value=True)
        self.cp_yaratici_mod = ctk.StringVar(value="off")
        self.cp_cakisma_mod = ctk.StringVar(value="rename")

        # --- LORA ---
        self.lr_kaynak = ctk.StringVar()
        self.lr_chk_taban = ctk.BooleanVar(value=True)
        self.lr_chk_kategori = ctk.BooleanVar(value=True)
        self.lr_chk_resim = ctk.BooleanVar(value=True)
        self.lr_yaratici_mod = ctk.StringVar(value="off")
        self.lr_cakisma_mod = ctk.StringVar(value="rename")

        # --- TEMİZLİK ---
        self.tm_kaynak = ctk.StringVar()
        self.tm_hedef = ctk.StringVar()
        self.tm_chk_puan = ctk.BooleanVar(value=True)
        self.tm_chk_eski = ctk.BooleanVar(value=True)
        self.tm_min_puan = ctk.DoubleVar(value=4.0)
        self.tm_cakisma_mod = ctk.StringVar(value="rename")

        # --- İSİM & TRIGGER (RENAME) ---
        self.rn_kaynak = ctk.StringVar()
        self.rn_mode = ctk.StringVar(value="meaningless")
        self.rn_chk_trigger = ctk.BooleanVar(value=True)
        self.rn_cakisma_mod = ctk.StringVar(value="rename")

        self.istatistik_yeniden_adlandirilan = 0
        self.istatistik_trigger_dolduruldu = 0

        self.istatistik_tasinan = 0
        self.istatistik_ayiklanan = 0
        self.istatistik_bos_klasor = 0

        self._creator_text_cp = ""
        self._creator_text_lr = ""

        self.ayarlari_yukle()

        ctk.set_appearance_mode("dark")
        self.geometry("1180x900")

        self.arayuz_ciz()
        self.ayarlari_uygula_widget()
        self.protocol("WM_DELETE_WINDOW", self.kapatirken_kaydet)

    # ------------------------------------------------------------------
    # UI construction
    # ------------------------------------------------------------------
    def arayuz_ciz(self):
        for w in self.winfo_children():
            w.destroy()

        self.title(t("app_title", self.lang))
        self.configure(fg_color=BG_MAIN)

        self.grid_columnconfigure(0, weight=0)
        self.grid_columnconfigure(1, weight=1)
        self.grid_rowconfigure(0, weight=0)
        self.grid_rowconfigure(1, weight=0)
        self.grid_rowconfigure(2, weight=3)
        self.grid_rowconfigure(3, weight=2)

        # Decorative gradient accent strip (indigo -> violet -> pink)
        gradient_canvas = tk.Canvas(self, height=4, highlightthickness=0, bd=0)
        gradient_canvas.grid(row=0, column=0, columnspan=2, sticky="ew")
        gradient_canvas.bind("<Configure>", lambda e: draw_gradient_bar(gradient_canvas, e.width, e.height))

        # Header
        header = ctk.CTkFrame(self, fg_color=BG_HEADER, corner_radius=0)
        header.grid(row=1, column=0, columnspan=2, sticky="ew")

        title_frame = ctk.CTkFrame(header, fg_color="transparent")
        title_frame.pack(side="left", padx=20, pady=12)
        ctk.CTkLabel(title_frame, text="LoRA Librarian", font=("Segoe UI", 16, "bold")).pack(anchor="w")
        ctk.CTkLabel(title_frame, text=f"v{APP_VERSION}", font=("Segoe UI", 10), text_color=TEXT_MUTED).pack(anchor="w")

        controls_frame = ctk.CTkFrame(header, fg_color="transparent")
        controls_frame.pack(side="right", padx=20, pady=12)

        theme_values = [t("theme_dark", self.lang), t("theme_light", self.lang)]
        self.theme_seg = ctk.CTkSegmentedButton(controls_frame, values=theme_values, command=self._on_theme_change, corner_radius=CORNER_BTN, selected_color=ACCENT, selected_hover_color=ACCENT_HOVER)
        current_theme_display = t("theme_dark", self.lang) if self.theme == "dark" else t("theme_light", self.lang)
        self.theme_seg.set(current_theme_display)
        self.theme_seg.pack(side="right", padx=(10, 0))

        lang_values = [LANG_LABELS[c] for c in LANG_CODES]
        self.lang_seg = ctk.CTkSegmentedButton(controls_frame, values=lang_values, command=self._on_lang_change, corner_radius=CORNER_BTN, selected_color=ACCENT, selected_hover_color=ACCENT_HOVER)
        self.lang_seg.set(LANG_LABELS.get(self.lang, LANG_LABELS["tr"]))
        self.lang_seg.pack(side="right")

        api_frame = ctk.CTkFrame(header, fg_color="transparent")
        api_frame.pack(side="right", padx=(0, 20), pady=12)
        ctk.CTkLabel(api_frame, text=t("api_key_label", self.lang), font=("Segoe UI", 11, "bold")).pack(side="left", padx=(0, 8))
        ctk.CTkEntry(api_frame, textvariable=self.api_key, width=220, show="*", corner_radius=CORNER_INPUT).pack(side="left")

        # Sidebar navigation
        sidebar = ctk.CTkFrame(self, fg_color="transparent", width=200)
        sidebar.grid(row=2, column=0, sticky="ns", padx=(16, 8), pady=(14, 8))
        sidebar.grid_propagate(False)

        self._nav_items = [("cp", "tab_checkpoint"), ("lr", "tab_lora"), ("tm", "tab_clean"), ("rn", "tab_rename")]
        self.nav_buttons = {}
        for key, label_key in self._nav_items:
            btn = ctk.CTkButton(
                sidebar, text=t(label_key, self.lang), anchor="w", corner_radius=CORNER_BTN,
                fg_color="transparent", text_color=SIDEBAR_TEXT, hover_color=SIDEBAR_ITEM_HOVER,
                command=lambda k=key: self.show_page(k),
            )
            btn.pack(fill="x", pady=4)
            self.nav_buttons[key] = btn

        # Content area (pages stacked, one raised at a time). The outer
        # container is the single scrollable region; each page is a
        # plain CTkFrame inside it - CTkScrollableFrame.tkraise() does
        # not reliably reorder stacking in customtkinter, so the pages
        # themselves must be plain frames for the raise-to-show trick
        # to work.
        content_container = ctk.CTkScrollableFrame(self, fg_color="transparent")
        content_container.grid(row=2, column=1, sticky="nsew", padx=(0, 16), pady=(14, 8))
        content_container.grid_rowconfigure(0, weight=1)
        content_container.grid_columnconfigure(0, weight=1)

        self.tab_cp = ctk.CTkFrame(content_container, fg_color="transparent")
        self.tab_lr = ctk.CTkFrame(content_container, fg_color="transparent")
        self.tab_tm = ctk.CTkFrame(content_container, fg_color="transparent")
        self.tab_rn = ctk.CTkFrame(content_container, fg_color="transparent")
        for frame in (self.tab_cp, self.tab_lr, self.tab_tm, self.tab_rn):
            frame.grid(row=0, column=0, sticky="new")

        self.sekme_checkpoint_doldur()
        self.sekme_lora_doldur()
        self.sekme_temizle_doldur()
        self.sekme_rename_doldur()

        self.show_page(getattr(self, "current_page", "cp"))

        # Log / process panel - spans full width, beneath sidebar + content
        log_frame = ctk.CTkFrame(self, fg_color=CARD_BG, corner_radius=CORNER_CARD, border_width=1, border_color=BORDER)
        log_frame.grid(row=3, column=0, columnspan=2, sticky="nsew", padx=16, pady=(8, 16))

        baslik_frame = ctk.CTkFrame(log_frame, fg_color="transparent")
        baslik_frame.pack(fill="x", padx=14, pady=(12, 0))

        self.lbl_durum = ctk.CTkLabel(baslik_frame, text=f'{t("status_label_prefix", self.lang)} {t("status_waiting", self.lang)}', font=("Segoe UI", 12, "bold"))
        self.lbl_durum.pack(side="left")

        self.lbl_yuzde = ctk.CTkLabel(baslik_frame, text="%0", font=("Segoe UI", 14, "bold"), text_color=ACCENT)
        self.lbl_yuzde.pack(side="right")

        self.progress_bar = ctk.CTkProgressBar(log_frame, progress_color=ACCENT, corner_radius=CORNER_INPUT)
        self.progress_bar.pack(fill="x", padx=14, pady=(8, 8))
        self.progress_bar.set(0)

        self.log_kutusu = ctk.CTkTextbox(log_frame, state="disabled", font=("Consolas", 12), text_color=ACCENT, fg_color=LOG_BG, corner_radius=CORNER_INPUT)
        self.log_kutusu.pack(fill="both", expand=True, padx=14, pady=(0, 14))
        self.log_yaz(t("log_ready", self.lang))

    def show_page(self, key):
        self.current_page = key
        frames = {"cp": self.tab_cp, "lr": self.tab_lr, "tm": self.tab_tm, "rn": self.tab_rn}
        frames[key].tkraise()
        for k, btn in self.nav_buttons.items():
            if k == key:
                btn.configure(fg_color=ACCENT, text_color="white")
            else:
                btn.configure(fg_color="transparent", text_color=SIDEBAR_TEXT)

    def _on_lang_change(self, value):
        for code, label in LANG_LABELS.items():
            if label == value:
                self.lang = code
                break
        self._creator_text_cp = self.metin_kutusunu_oku(self.cp_yaratici_kutu) if hasattr(self, "cp_yaratici_kutu") else self._creator_text_cp
        self._creator_text_lr = self.metin_kutusunu_oku(self.lr_yaratici_kutu) if hasattr(self, "lr_yaratici_kutu") else self._creator_text_lr
        self.arayuz_ciz()
        self.ayarlari_uygula_widget()

    def _on_theme_change(self, value):
        self.theme = "dark" if value == t("theme_dark", self.lang) else "light"
        ctk.set_appearance_mode(self.theme)

    def yol_secici_ciz(self, parent, kaynak_var, hedef_var=None, metin=None):
        frame = ctk.CTkFrame(parent, fg_color=CARD_BG, corner_radius=CORNER_CARD, border_width=1, border_color=BORDER)
        frame.pack(fill="x", pady=10)

        ctk.CTkLabel(frame, text=metin, font=("Segoe UI", 11, "bold")).grid(row=0, column=0, sticky="w", padx=14, pady=(14, 0))
        ctk.CTkEntry(frame, textvariable=kaynak_var, width=550, corner_radius=CORNER_INPUT).grid(row=1, column=0, padx=14, pady=8, sticky="w")
        ctk.CTkButton(frame, text=t("browse", self.lang), width=90, corner_radius=CORNER_BTN, fg_color=ACCENT, hover_color=ACCENT_HOVER, command=lambda: self.klasor_sec(kaynak_var)).grid(row=1, column=1, pady=8, padx=(0, 14))

        if hedef_var is not None:
            ctk.CTkLabel(frame, text=t("folder_trash", self.lang), font=("Segoe UI", 11, "bold")).grid(row=2, column=0, sticky="w", padx=14, pady=(10, 0))
            ctk.CTkEntry(frame, textvariable=hedef_var, width=550, corner_radius=CORNER_INPUT).grid(row=3, column=0, padx=14, pady=(8, 14), sticky="w")
            ctk.CTkButton(frame, text=t("browse", self.lang), width=90, corner_radius=CORNER_BTN, fg_color=ACCENT, hover_color=ACCENT_HOVER, command=lambda: self.klasor_sec(hedef_var)).grid(row=3, column=1, pady=(8, 14), padx=(0, 14))

    def yaratici_menu_guncelle(self, kod, kutu):
        kutu.configure(state="normal" if kod == "list" else "disabled")

    def _conflict_display_values(self):
        return [t(CONFLICT_KEYS[c], self.lang) for c in CONFLICT_CODES]

    def _conflict_display_from_code(self, code):
        return t(CONFLICT_KEYS.get(code, "conflict_rename"), self.lang)

    def _conflict_code_from_display(self, display):
        for c in CONFLICT_CODES:
            if t(CONFLICT_KEYS[c], self.lang) == display:
                return c
        return "rename"

    def _creator_display_values(self):
        return [t(CREATOR_KEYS[c], self.lang) for c in CREATOR_CODES]

    def _creator_display_from_code(self, code):
        return t(CREATOR_KEYS.get(code, "creator_mode_off"), self.lang)

    def _creator_code_from_display(self, display):
        for c in CREATOR_CODES:
            if t(CREATOR_KEYS[c], self.lang) == display:
                return c
        return "off"

    def _rename_mode_display_values(self):
        return [t(RENAME_MODE_KEYS[c], self.lang) for c in RENAME_MODE_CODES]

    def _rename_mode_display_from_code(self, code):
        return t(RENAME_MODE_KEYS.get(code, "rename_mode_meaningless"), self.lang)

    def _rename_mode_code_from_display(self, display):
        for c in RENAME_MODE_CODES:
            if t(RENAME_MODE_KEYS[c], self.lang) == display:
                return c
        return "meaningless"

    def ayarlar_ciz(self, parent, mod_tipi):
        chk_taban = self.cp_chk_taban if mod_tipi == "cp" else self.lr_chk_taban
        chk_resim = self.cp_chk_resim if mod_tipi == "cp" else self.lr_chk_resim
        chk_kategori = self.cp_chk_kategori if mod_tipi == "cp" else self.lr_chk_kategori
        yaratici_mod = self.cp_yaratici_mod if mod_tipi == "cp" else self.lr_yaratici_mod
        cakisma_mod = self.cp_cakisma_mod if mod_tipi == "cp" else self.lr_cakisma_mod

        ust_frame = ctk.CTkFrame(parent, fg_color="transparent")
        ust_frame.pack(fill="x", padx=10, pady=5)

        ctk.CTkSwitch(ust_frame, text=t("switch_base_model", self.lang), variable=chk_taban).grid(row=0, column=0, sticky="w", pady=5)
        ctk.CTkSwitch(ust_frame, text=t("switch_fetch_meta", self.lang), variable=chk_resim).grid(row=0, column=1, sticky="w", padx=30, pady=5)
        ctk.CTkSwitch(ust_frame, text=t("switch_category", self.lang), variable=chk_kategori).grid(row=1, column=0, columnspan=2, sticky="w", pady=10)

        yaratici_frame = ctk.CTkFrame(parent, fg_color=CARD_BG, corner_radius=CORNER_CARD, border_width=1, border_color=BORDER)
        yaratici_frame.pack(fill="x", padx=10, pady=5)

        ctk.CTkLabel(yaratici_frame, text=t("creator_folder_label", self.lang), font=("Segoe UI", 12, "bold")).grid(row=0, column=0, sticky="w", padx=14, pady=14)

        yaratici_kutu = ctk.CTkTextbox(yaratici_frame, height=80, width=420, corner_radius=CORNER_INPUT)

        opt = ctk.CTkOptionMenu(
            yaratici_frame,
            values=self._creator_display_values(),
            corner_radius=CORNER_BTN, fg_color=ACCENT, button_color=ACCENT, button_hover_color=ACCENT_HOVER,
            command=lambda disp, kutu=yaratici_kutu, var=yaratici_mod: (
                var.set(self._creator_code_from_display(disp)),
                self.yaratici_menu_guncelle(var.get(), kutu),
            ),
        )
        opt.set(self._creator_display_from_code(yaratici_mod.get()))
        opt.grid(row=0, column=1, sticky="w", padx=14, pady=14)

        ctk.CTkLabel(yaratici_frame, text=t("creator_hint", self.lang), font=("Segoe UI", 10, "italic"), text_color=TEXT_MUTED).grid(row=1, column=0, columnspan=2, sticky="w", padx=14, pady=(0, 5))

        yaratici_kutu.grid(row=2, column=0, columnspan=2, padx=14, pady=(0, 14))
        yaratici_kutu.configure(state="normal" if yaratici_mod.get() == "list" else "disabled")

        if mod_tipi == "cp":
            self.cp_yaratici_kutu = yaratici_kutu
            self.metin_kutusunu_doldur(yaratici_kutu, self._creator_text_cp)
        else:
            self.lr_yaratici_kutu = yaratici_kutu
            self.metin_kutusunu_doldur(yaratici_kutu, self._creator_text_lr)
        if yaratici_mod.get() != "list":
            yaratici_kutu.configure(state="disabled")

        cakisma_frame = ctk.CTkFrame(parent, fg_color="transparent")
        cakisma_frame.pack(fill="x", padx=10, pady=5)
        ctk.CTkLabel(cakisma_frame, text=t("conflict_label", self.lang), font=("Segoe UI", 12, "bold")).pack(side="left", padx=10)
        opt2 = ctk.CTkOptionMenu(
            cakisma_frame,
            values=self._conflict_display_values(),
            corner_radius=CORNER_BTN, fg_color=ACCENT, button_color=ACCENT, button_hover_color=ACCENT_HOVER,
            command=lambda disp, var=cakisma_mod: var.set(self._conflict_code_from_display(disp)),
        )
        opt2.set(self._conflict_display_from_code(cakisma_mod.get()))
        opt2.pack(side="left", padx=10)

    def sekme_checkpoint_doldur(self):
        self.yol_secici_ciz(self.tab_cp, self.cp_kaynak, metin=t("folder_checkpoint", self.lang))
        self.ayarlar_ciz(self.tab_cp, "cp")
        self.btn_cp = ctk.CTkButton(self.tab_cp, text=t("btn_organize_checkpoint", self.lang), corner_radius=CORNER_BTN, height=38, fg_color="#2b7a0b", hover_color="#3e9915", command=lambda: self.baslat_thread("checkpoint"))
        self.btn_cp.pack(pady=10)

    def sekme_lora_doldur(self):
        self.yol_secici_ciz(self.tab_lr, self.lr_kaynak, metin=t("folder_lora", self.lang))
        self.ayarlar_ciz(self.tab_lr, "lr")
        self.btn_lr = ctk.CTkButton(self.tab_lr, text=t("btn_organize_lora", self.lang), corner_radius=CORNER_BTN, height=38, fg_color="#0b5b7a", hover_color="#157199", command=lambda: self.baslat_thread("lora"))
        self.btn_lr.pack(pady=10)

    def sekme_temizle_doldur(self):
        self.yol_secici_ciz(self.tab_tm, self.tm_kaynak, self.tm_hedef, metin=t("folder_scan", self.lang))

        c_frame = ctk.CTkFrame(self.tab_tm, fg_color="transparent")
        c_frame.pack(anchor="w", padx=20, pady=10)

        ctk.CTkSwitch(c_frame, text=t("switch_old_versions", self.lang), variable=self.tm_chk_eski, progress_color=ACCENT).grid(row=0, column=0, sticky="w", pady=10)
        ctk.CTkSwitch(c_frame, text=t("switch_low_rating", self.lang), variable=self.tm_chk_puan, progress_color=ACCENT).grid(row=1, column=0, sticky="w", pady=(10, 0))

        slider_frame = ctk.CTkFrame(c_frame, fg_color="transparent")
        slider_frame.grid(row=2, column=0, sticky="w", pady=5, padx=30)
        ctk.CTkLabel(slider_frame, text=t("min_rating_label", self.lang)).pack(side="left")
        puan_lbl = ctk.CTkLabel(slider_frame, text=f"{self.tm_min_puan.get():.1f}", width=30)
        slider = ctk.CTkSlider(slider_frame, from_=0.0, to=5.0, number_of_steps=50, variable=self.tm_min_puan, progress_color=ACCENT, button_color=ACCENT, button_hover_color=ACCENT_HOVER, command=lambda v: puan_lbl.configure(text=f"{v:.1f}"))
        slider.pack(side="left", padx=10)
        puan_lbl.pack(side="left")

        cakisma_frame = ctk.CTkFrame(self.tab_tm, fg_color="transparent")
        cakisma_frame.pack(anchor="w", padx=20, pady=5)
        ctk.CTkLabel(cakisma_frame, text=t("conflict_trash_label", self.lang), font=("Segoe UI", 12, "bold")).pack(side="left")
        opt3 = ctk.CTkOptionMenu(
            cakisma_frame,
            values=self._conflict_display_values(),
            corner_radius=CORNER_BTN, fg_color=ACCENT, button_color=ACCENT, button_hover_color=ACCENT_HOVER,
            command=lambda disp: self.tm_cakisma_mod.set(self._conflict_code_from_display(disp)),
        )
        opt3.set(self._conflict_display_from_code(self.tm_cakisma_mod.get()))
        opt3.pack(side="left", padx=10)

        self.btn_tm = ctk.CTkButton(self.tab_tm, text=t("btn_start_clean", self.lang), corner_radius=CORNER_BTN, height=38, fg_color="#b5261a", hover_color="#d63424", command=lambda: self.baslat_thread("temizle"))
        self.btn_tm.pack(pady=20)

    def sekme_rename_doldur(self):
        self.yol_secici_ciz(self.tab_rn, self.rn_kaynak, metin=t("folder_lora", self.lang))

        info_frame = ctk.CTkFrame(self.tab_rn, fg_color=CARD_BG, corner_radius=CORNER_CARD, border_width=1, border_color=BORDER)
        info_frame.pack(fill="x", padx=10, pady=(5, 10))
        ctk.CTkLabel(info_frame, text=t("rename_info_text", self.lang), font=("Segoe UI", 10, "italic"), text_color=TEXT_MUTED, justify="left", wraplength=680).pack(anchor="w", padx=14, pady=14)

        opts_frame = ctk.CTkFrame(self.tab_rn, fg_color="transparent")
        opts_frame.pack(fill="x", padx=10, pady=5)

        ctk.CTkLabel(opts_frame, text=t("rename_mode_label", self.lang), font=("Segoe UI", 12, "bold")).grid(row=0, column=0, sticky="w", pady=10)
        opt_rn = ctk.CTkOptionMenu(
            opts_frame,
            values=self._rename_mode_display_values(),
            corner_radius=CORNER_BTN, fg_color=ACCENT, button_color=ACCENT, button_hover_color=ACCENT_HOVER,
            command=lambda disp: self.rn_mode.set(self._rename_mode_code_from_display(disp)),
        )
        opt_rn.set(self._rename_mode_display_from_code(self.rn_mode.get()))
        opt_rn.grid(row=0, column=1, sticky="w", padx=10, pady=10)

        ctk.CTkSwitch(opts_frame, text=t("switch_fill_trigger", self.lang), variable=self.rn_chk_trigger, progress_color=ACCENT).grid(row=1, column=0, columnspan=2, sticky="w", pady=10)

        cakisma_frame = ctk.CTkFrame(self.tab_rn, fg_color="transparent")
        cakisma_frame.pack(fill="x", padx=10, pady=5)
        ctk.CTkLabel(cakisma_frame, text=t("conflict_label", self.lang), font=("Segoe UI", 12, "bold")).pack(side="left", padx=10)
        opt_rn2 = ctk.CTkOptionMenu(
            cakisma_frame,
            values=self._conflict_display_values(),
            corner_radius=CORNER_BTN, fg_color=ACCENT, button_color=ACCENT, button_hover_color=ACCENT_HOVER,
            command=lambda disp: self.rn_cakisma_mod.set(self._conflict_code_from_display(disp)),
        )
        opt_rn2.set(self._conflict_display_from_code(self.rn_cakisma_mod.get()))
        opt_rn2.pack(side="left", padx=10)

        self.btn_rn = ctk.CTkButton(self.tab_rn, text=t("btn_start_rename", self.lang), corner_radius=CORNER_BTN, height=38, fg_color="#7a4a0b", hover_color="#996015", command=lambda: self.baslat_thread("rename"))
        self.btn_rn.pack(pady=20)

    # ------------------------------------------------------------------
    # Settings persistence (Ayarlar / Settings)
    # ------------------------------------------------------------------
    def metin_kutusunu_doldur(self, kutu, metin):
        kutu.configure(state="normal")
        kutu.delete("1.0", "end")
        if metin:
            kutu.insert("1.0", metin)

    def metin_kutusunu_oku(self, kutu):
        return kutu.get("1.0", "end-1c").strip()

    def ayarlari_yukle(self):
        self.theme = "dark"
        if not os.path.exists(SETTINGS_PATH):
            return
        try:
            with open(SETTINGS_PATH, "r", encoding="utf-8") as f:
                ayarlar = json.load(f)
            self.lang = ayarlar.get("lang", "tr")
            self.theme = ayarlar.get("theme", "dark")
            self._pending_geometry = ayarlar.get("geometry", "1180x900")
            self.api_key.set(ayarlar.get("api_key", ""))

            if "cp" in ayarlar:
                d = ayarlar["cp"]
                self.cp_kaynak.set(d.get("kaynak", ""))
                self.cp_chk_taban.set(d.get("taban", True))
                self.cp_chk_kategori.set(d.get("kategori", False))
                self.cp_chk_resim.set(d.get("resim", True))
                self.cp_yaratici_mod.set(d.get("yaratici_mod", "off"))
                self.cp_cakisma_mod.set(d.get("cakisma_mod", "rename"))
                self._creator_text_cp = d.get("yaratici_liste", "")

            if "lr" in ayarlar:
                d = ayarlar["lr"]
                self.lr_kaynak.set(d.get("kaynak", ""))
                self.lr_chk_taban.set(d.get("taban", True))
                self.lr_chk_kategori.set(d.get("kategori", True))
                self.lr_chk_resim.set(d.get("resim", True))
                self.lr_yaratici_mod.set(d.get("yaratici_mod", "off"))
                self.lr_cakisma_mod.set(d.get("cakisma_mod", "rename"))
                self._creator_text_lr = d.get("yaratici_liste", "")

            if "tm" in ayarlar:
                d = ayarlar["tm"]
                self.tm_kaynak.set(d.get("kaynak", ""))
                self.tm_hedef.set(d.get("hedef", ""))
                self.tm_chk_puan.set(d.get("puan", True))
                self.tm_chk_eski.set(d.get("eski", True))
                self.tm_min_puan.set(d.get("min_puan", 4.0))
                self.tm_cakisma_mod.set(d.get("cakisma_mod", "rename"))

            if "rn" in ayarlar:
                d = ayarlar["rn"]
                self.rn_kaynak.set(d.get("kaynak", ""))
                self.rn_mode.set(d.get("mode", "meaningless"))
                self.rn_chk_trigger.set(d.get("trigger", True))
                self.rn_cakisma_mod.set(d.get("cakisma_mod", "rename"))
        except Exception:
            pass

    def ayarlari_uygula_widget(self):
        """Apply the geometry saved from a previous run, once widgets exist."""
        geo = getattr(self, "_pending_geometry", None)
        if geo:
            try:
                self.geometry(geo)
            except Exception:
                pass

    def kapatirken_kaydet(self):
        ayarlar = {
            "lang": self.lang,
            "theme": self.theme,
            "geometry": self.geometry(),
            "api_key": self.api_key.get(),
            "cp": {
                "kaynak": self.cp_kaynak.get(), "taban": self.cp_chk_taban.get(), "kategori": self.cp_chk_kategori.get(),
                "resim": self.cp_chk_resim.get(), "yaratici_mod": self.cp_yaratici_mod.get(), "cakisma_mod": self.cp_cakisma_mod.get(),
                "yaratici_liste": self.metin_kutusunu_oku(self.cp_yaratici_kutu),
            },
            "lr": {
                "kaynak": self.lr_kaynak.get(), "taban": self.lr_chk_taban.get(), "kategori": self.lr_chk_kategori.get(),
                "resim": self.lr_chk_resim.get(), "yaratici_mod": self.lr_yaratici_mod.get(), "cakisma_mod": self.lr_cakisma_mod.get(),
                "yaratici_liste": self.metin_kutusunu_oku(self.lr_yaratici_kutu),
            },
            "tm": {
                "kaynak": self.tm_kaynak.get(), "hedef": self.tm_hedef.get(), "puan": self.tm_chk_puan.get(),
                "eski": self.tm_chk_eski.get(), "min_puan": self.tm_min_puan.get(), "cakisma_mod": self.tm_cakisma_mod.get(),
            },
            "rn": {
                "kaynak": self.rn_kaynak.get(), "mode": self.rn_mode.get(),
                "trigger": self.rn_chk_trigger.get(), "cakisma_mod": self.rn_cakisma_mod.get(),
            },
        }
        try:
            with open(SETTINGS_PATH, "w", encoding="utf-8") as f:
                json.dump(ayarlar, f, indent=4, ensure_ascii=False)
        except Exception:
            pass
        self._hash_cache_kaydet()
        self.destroy()

    def _hash_cache_yukle(self):
        if os.path.exists(HASH_CACHE_PATH):
            try:
                with open(HASH_CACHE_PATH, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception:
                return {}
        return {}

    def _hash_cache_kaydet(self):
        try:
            with open(HASH_CACHE_PATH, "w", encoding="utf-8") as f:
                json.dump(self.hash_cache, f)
        except Exception:
            pass

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------
    def klasor_sec(self, degisken):
        yol = filedialog.askdirectory()
        if yol:
            degisken.set(yol)

    def log_yaz(self, mesaj):
        self.log_kutusu.configure(state="normal")
        self.log_kutusu.insert("end", mesaj + "\n")
        self.log_kutusu.see("end")
        self.log_kutusu.configure(state="disabled")

    def get_hash(self, filepath):
        """SHA-256 hash with a size+mtime cache so re-scanning an
        already-processed library doesn't re-hash unchanged files
        (optimization / optimizasyon)."""
        try:
            stat = os.stat(filepath)
            cache_key = filepath
            cached = self.hash_cache.get(cache_key)
            if cached and cached.get("mtime") == stat.st_mtime and cached.get("size") == stat.st_size:
                return cached["hash"]
        except Exception:
            stat = None

        self.log_yaz(t("log_hash_reading", self.lang))
        sha256 = hashlib.sha256()
        with open(filepath, "rb") as f:
            for chunk in iter(lambda: f.read(1024 * 1024), b""):
                sha256.update(chunk)
        digest = sha256.hexdigest()

        if stat is not None:
            self.hash_cache[filepath] = {"mtime": stat.st_mtime, "size": stat.st_size, "hash": digest}
        return digest

    def _resim_uzantisi_belirle(self, content_type, url):
        """Decide the correct file extension for a downloaded cover image
        based on its real Content-Type (falls back to the URL's own
        extension), instead of blindly writing every download as .png -
        which produced unreadable files whenever the actual image was a
        JPEG/WEBP or the download itself failed."""
        content_type = (content_type or "").lower()
        if "jpeg" in content_type or "jpg" in content_type:
            return ".jpg"
        if "webp" in content_type:
            return ".webp"
        if "png" in content_type:
            return ".png"
        url_ext = os.path.splitext(url.split("?")[0])[1].lower()
        if url_ext in (".jpg", ".jpeg", ".png", ".webp"):
            return url_ext
        return ".jpg"

    def dosya_temizle_adi(self, isim):
        for c in ['/', '\\', ':', '*', '?', '"', '<', '>', '|']:
            isim = isim.replace(c, "_")
        return isim.strip() or "_"

    def bos_klasorleri_temizle(self, baslangic_dizini):
        temizlenen = 0
        for root, dirs, files in os.walk(baslangic_dizini, topdown=False):
            for name in dirs:
                klasor_yolu = os.path.join(root, name)
                if not os.listdir(klasor_yolu):
                    try:
                        os.rmdir(klasor_yolu)
                        temizlenen += 1
                    except Exception:
                        pass
        if temizlenen > 0:
            self.istatistik_bos_klasor += temizlenen
            self.log_yaz(t("log_empty_folders", self.lang, count=temizlenen))

    def dosyalari_tasi(self, dosya_adi, kaynak_klasor, hedef_tam_yol, cakisma_kodu, islem_tipi):
        if not os.path.exists(hedef_tam_yol):
            try:
                os.makedirs(hedef_tam_yol)
            except Exception:
                self.log_yaz(t("log_folder_error", self.lang))
                return

        base_adi = os.path.splitext(dosya_adi)[0]
        aranan = base_adi + "."
        basarili_tasima = False

        for f in os.listdir(kaynak_klasor):
            if f.startswith(aranan) or f == dosya_adi:
                eski = os.path.join(kaynak_klasor, f)
                yeni = os.path.join(hedef_tam_yol, f)

                if os.path.abspath(eski) == os.path.abspath(yeni):
                    continue

                if os.path.exists(yeni):
                    if cakisma_kodu == "skip":
                        self.log_yaz(t("log_skipped_exists", self.lang, file=f))
                        continue
                    elif cakisma_kodu == "rename":
                        isim, uzanti = os.path.splitext(f)
                        sayac = 1
                        while os.path.exists(yeni):
                            yeni = os.path.join(hedef_tam_yol, f"{isim}_{sayac}{uzanti}")
                            sayac += 1
                        self.log_yaz(t("log_renamed", self.lang, file=os.path.basename(yeni)))
                    elif cakisma_kodu == "overwrite":
                        try:
                            os.remove(yeni)
                        except Exception:
                            pass
                try:
                    shutil.move(eski, yeni)
                    basarili_tasima = True
                    if cakisma_kodu != "rename" or not os.path.exists(yeni):
                        self.log_yaz(t("log_moved", self.lang, folder=os.path.basename(hedef_tam_yol)))
                except Exception:
                    self.log_yaz(t("log_move_failed", self.lang))

        if basarili_tasima:
            if islem_tipi in ["checkpoint", "lora"]:
                self.istatistik_tasinan += 1
            else:
                self.istatistik_ayiklanan += 1

    # ------------------------------------------------------------------
    # Main engine
    # ------------------------------------------------------------------
    def baslat_thread(self, mod):
        if mod == "checkpoint":
            kaynak = self.cp_kaynak.get()
            hedef = kaynak
            config = {"taban": self.cp_chk_taban.get(), "kategori": self.cp_chk_kategori.get(), "resim": self.cp_chk_resim.get(),
                      "y_mod": self.cp_yaratici_mod.get(), "y_liste": self.metin_kutusunu_oku(self.cp_yaratici_kutu), "cakisma": self.cp_cakisma_mod.get()}
            if not kaynak:
                return messagebox.showwarning(t("dialog_warning_title", self.lang), t("dialog_warning_no_folder", self.lang))
        elif mod == "lora":
            kaynak = self.lr_kaynak.get()
            hedef = kaynak
            config = {"taban": self.lr_chk_taban.get(), "kategori": self.lr_chk_kategori.get(), "resim": self.lr_chk_resim.get(),
                      "y_mod": self.lr_yaratici_mod.get(), "y_liste": self.metin_kutusunu_oku(self.lr_yaratici_kutu), "cakisma": self.lr_cakisma_mod.get()}
            if not kaynak:
                return messagebox.showwarning(t("dialog_warning_title", self.lang), t("dialog_warning_no_folder", self.lang))
        elif mod == "rename":
            kaynak = self.rn_kaynak.get()
            hedef = kaynak
            config = {"mode": self.rn_mode.get(), "trigger": self.rn_chk_trigger.get(), "cakisma": self.rn_cakisma_mod.get()}
            if not kaynak:
                return messagebox.showwarning(t("dialog_warning_title", self.lang), t("dialog_warning_no_folder", self.lang))
        else:
            kaynak, hedef = self.tm_kaynak.get(), self.tm_hedef.get()
            config = {"puan": self.tm_chk_puan.get(), "min_p": self.tm_min_puan.get(), "eski": self.tm_chk_eski.get(), "cakisma": self.tm_cakisma_mod.get()}
            if not kaynak or not hedef:
                return messagebox.showwarning(t("dialog_warning_title", self.lang), t("dialog_warning_no_scan_trash", self.lang))

        if self.islem_devam_ediyor:
            return
        self.btn_cp.configure(state="disabled")
        self.btn_lr.configure(state="disabled")
        self.btn_tm.configure(state="disabled")
        self.btn_rn.configure(state="disabled")
        motor = self.ana_motor_rename if mod == "rename" else self.ana_motor
        threading.Thread(target=motor, args=(mod, kaynak, hedef, config), daemon=True).start()

    def ana_motor(self, mod, kaynak, hedef, config):
        self.islem_devam_ediyor = True

        self.istatistik_tasinan = 0
        self.istatistik_ayiklanan = 0
        self.istatistik_bos_klasor = 0
        self.progress_bar.set(0)
        self.lbl_yuzde.configure(text="%0")
        self.lbl_durum.configure(text=f'{t("status_label_prefix", self.lang)} {t("status_running", self.lang)}')

        api = self.api_key.get()
        headers = {"Authorization": f"Bearer {api}"} if api else {}
        model_gecmisi = {}

        hedef_yaraticilar = []
        if mod in ["checkpoint", "lora"] and config["y_mod"] == "list":
            hedef_yaraticilar = [x.strip().lower() for x in config["y_liste"].split("\n") if x.strip()]

        self.log_yaz(t("log_system_started", self.lang, mode=mod.upper()))

        islem_listesi = []
        for root, dirs, files in os.walk(kaynak):
            for file in files:
                if file.endswith((".safetensors", ".ckpt")):
                    islem_listesi.append((root, file))

        toplam_model = len(islem_listesi)
        self.log_yaz(t("log_total_models", self.lang, count=toplam_model))

        unknown_base = t("unknown_base", self.lang)
        unknown_creator = t("unknown_creator", self.lang)

        for index, (root, file) in enumerate(islem_listesi):
            dosya_yolu = os.path.join(root, file)
            if not os.path.exists(dosya_yolu):
                continue

            base_adi = os.path.splitext(file)[0]
            self.log_yaz(t("log_model", self.lang, file=file))

            resim_var = any(os.path.exists(os.path.join(root, base_adi + ext)) for ext in [".png", ".jpg", ".jpeg", ".webp"])
            json_var = any(os.path.exists(os.path.join(root, base_adi + ext)) for ext in [".json", ".civitai.info"])

            m_id, t_taban_raw, t_yaratici = None, None, unknown_creator
            t_tags = []
            api_lazim, model_verisi = True, None

            for info_p in [os.path.join(root, base_adi + ".json"), os.path.join(root, base_adi + ".civitai.info")]:
                if os.path.exists(info_p):
                    try:
                        with open(info_p, "r", encoding="utf-8") as f:
                            j = json.load(f)
                            m_id = j.get("modelId") or j.get("id")
                            t_taban_raw = j.get("baseModel")
                            t_yaratici = j.get("creator", {}).get("username", unknown_creator)
                            t_tags = j.get("tags", [])
                            if mod in ["checkpoint", "lora"] and config["y_mod"] == "off" and resim_var and (not config.get("kategori") or t_tags):
                                api_lazim = False
                    except Exception:
                        pass
                    break

            if mod == "temizle":
                api_lazim = True

            if api_lazim:
                if m_id:
                    url = f"https://{API_DOMAIN}/api/v1/model-versions/{m_id}"
                else:
                    url = f"https://{API_DOMAIN}/api/v1/model-versions/by-hash/{self.get_hash(dosya_yolu)}"
                try:
                    cevap = self.session.get(url, headers=headers, params=CIVITAI_CONTENT_PARAMS, timeout=10)
                    if cevap.status_code == 200:
                        model_verisi = cevap.json()
                        m_id = model_verisi.get("modelId")
                        t_taban_raw = model_verisi.get("baseModel", t_taban_raw)

                        kategori_lazim = config.get("kategori") and not t_tags
                        yaratici_lazim = config.get("y_mod") != "off" and t_yaratici == unknown_creator

                        if mod in ["checkpoint", "lora"] and m_id and (yaratici_lazim or kategori_lazim):
                            try:
                                model_ana_veri = self.session.get(f"https://{API_DOMAIN}/api/v1/models/{m_id}", headers=headers, params=CIVITAI_CONTENT_PARAMS, timeout=5)
                                if model_ana_veri.status_code == 200:
                                    ana_json = model_ana_veri.json()
                                    if yaratici_lazim:
                                        t_yaratici = ana_json.get("creator", {}).get("username", unknown_creator)
                                    if kategori_lazim:
                                        t_tags = ana_json.get("tags", [])
                            except Exception:
                                pass

                        if mod in ["checkpoint", "lora"] and not json_var and config.get("resim"):
                            try:
                                json_yolu = os.path.join(root, base_adi + ".json")
                                with open(json_yolu, "w", encoding="utf-8") as jf:
                                    if t_yaratici != unknown_creator:
                                        model_verisi["creator"] = {"username": t_yaratici}
                                    if t_tags:
                                        model_verisi["tags"] = t_tags
                                    json.dump(model_verisi, jf, indent=4)
                                self.log_yaz(t("log_api_saved", self.lang))
                            except Exception:
                                pass
                except Exception:
                    self.log_yaz(t("log_api_failed", self.lang))

            t_taban = self.dosya_temizle_adi(normalize_base_model(t_taban_raw, unknown_base))
            t_yaratici = self.dosya_temizle_adi(t_yaratici)

            t_kategori = ""
            if mod in ["checkpoint", "lora"] and config.get("kategori"):
                t_tags_lower = []
                for tag in t_tags:
                    if isinstance(tag, str):
                        t_tags_lower.append(tag.lower())
                    elif isinstance(tag, dict) and "name" in tag:
                        t_tags_lower.append(str(tag["name"]).lower())

                if "concept" in t_tags_lower or "konsept" in t_tags_lower:
                    t_kategori = t("category_concept", self.lang)
                elif "background" in t_tags_lower or "arkaplan" in t_tags_lower:
                    t_kategori = t("category_background", self.lang)

            if mod == "temizle" and model_verisi:
                v_id = model_verisi.get("id")
                rating = model_verisi.get("stats", {}).get("rating", 0)
                if config["puan"] and 0 < rating < config["min_p"]:
                    self.log_yaz(t("log_extracting_rating", self.lang, rating=rating))
                    self.dosyalari_tasi(file, root, os.path.join(hedef, t("folder_low_rated", self.lang)), config["cakisma"], mod)
                    continue
                if config["eski"] and m_id:
                    if m_id in model_gecmisi:
                        kayitli = model_gecmisi[m_id]
                        if v_id > kayitli["v_id"]:
                            self.dosyalari_tasi(kayitli["file"], kayitli["root"], os.path.join(hedef, t("folder_old_versions", self.lang)), config["cakisma"], mod)
                            model_gecmisi[m_id] = {"file": file, "v_id": v_id, "root": root}
                        elif v_id < kayitli["v_id"]:
                            self.dosyalari_tasi(file, root, os.path.join(hedef, t("folder_old_versions", self.lang)), config["cakisma"], mod)
                            continue
                    else:
                        model_gecmisi[m_id] = {"file": file, "v_id": v_id, "root": root}

            elif mod in ["checkpoint", "lora"]:
                if config["resim"] and not resim_var and model_verisi and model_verisi.get("images"):
                    try:
                        img_url = model_verisi["images"][0]["url"]
                        r_img = self.session.get(img_url, timeout=15)
                        if r_img.status_code == 200 and r_img.content:
                            ext = self._resim_uzantisi_belirle(r_img.headers.get("Content-Type", ""), img_url)
                            with open(os.path.join(root, base_adi + ext), "wb") as f:
                                f.write(r_img.content)
                            self.log_yaz(t("log_cover_downloaded", self.lang))
                        else:
                            self.log_yaz(t("log_cover_failed", self.lang))
                    except Exception:
                        self.log_yaz(t("log_cover_failed", self.lang))

                yol_parcalari = [kaynak]
                if config["taban"] and t_taban != unknown_base:
                    yol_parcalari.append(t_taban)
                if config["kategori"] and t_kategori:
                    yol_parcalari.append(t_kategori)
                if config["y_mod"] == "all" and t_yaratici != unknown_creator:
                    yol_parcalari.append(t_yaratici)
                elif config["y_mod"] == "list" and t_yaratici != unknown_creator:
                    if t_yaratici.lower() in hedef_yaraticilar:
                        yol_parcalari.append(t_yaratici)

                dinamik_hedef = os.path.join(*yol_parcalari)
                self.dosyalari_tasi(file, root, dinamik_hedef, config["cakisma"], mod)

            ilerleme_orani = (index + 1) / toplam_model if toplam_model > 0 else 1
            self.progress_bar.set(ilerleme_orani)
            self.lbl_yuzde.configure(text=f"%{int(ilerleme_orani * 100)}")
            if api_lazim:
                time.sleep(0.5)

        self.bos_klasorleri_temizle(kaynak)
        self._hash_cache_kaydet()

        ozet_metni = t(
            "summary_text", self.lang,
            moved=self.istatistik_tasinan,
            extracted=self.istatistik_ayiklanan,
            empty=self.istatistik_bos_klasor,
        )

        self.log_yaz(f'{t("log_summary_title", self.lang)}\n{ozet_metni}')
        self.lbl_durum.configure(text=f'{t("status_label_prefix", self.lang)} {t("status_done", self.lang)}')
        self.islem_devam_ediyor = False
        self.btn_cp.configure(state="normal")
        self.btn_lr.configure(state="normal")
        self.btn_tm.configure(state="normal")
        self.btn_rn.configure(state="normal")
        messagebox.showinfo(t("dialog_report_title", self.lang), ozet_metni)

    # ------------------------------------------------------------------
    # Rename & trigger-word engine
    # ------------------------------------------------------------------
    def rename_related_files(self, root, eski_base, yeni_base, cakisma_kodu):
        """Rename the model file itself and every companion file that
        shares its basename (.civitai.info, .json, preview images, .txt
        etc. - whatever Civitai Helper / A1111 created next to it)."""
        aranan = eski_base + "."
        yeniden_adlandirilan = []

        for f in list(os.listdir(root)):
            if not (f.startswith(aranan) or f == eski_base):
                continue
            ek = f[len(eski_base):]  # e.g. ".safetensors", ".civitai.info", ".preview.png"
            eski_yol = os.path.join(root, f)
            yeni_dosya_adi = yeni_base + ek
            yeni_yol = os.path.join(root, yeni_dosya_adi)

            if os.path.abspath(eski_yol) == os.path.abspath(yeni_yol):
                continue

            if os.path.exists(yeni_yol):
                if cakisma_kodu == "skip":
                    self.log_yaz(t("log_skipped_exists", self.lang, file=yeni_dosya_adi))
                    continue
                elif cakisma_kodu == "overwrite":
                    try:
                        os.remove(yeni_yol)
                    except Exception:
                        pass
                elif cakisma_kodu == "rename":
                    kok, uzanti = os.path.splitext(yeni_dosya_adi)
                    sayac = 1
                    while os.path.exists(yeni_yol):
                        yeni_yol = os.path.join(root, f"{kok}_{sayac}{uzanti}")
                        sayac += 1

            try:
                os.rename(eski_yol, yeni_yol)
                yeniden_adlandirilan.append(os.path.basename(yeni_yol))
            except Exception:
                self.log_yaz(t("log_move_failed", self.lang))

        return yeniden_adlandirilan

    def _trigger_kelimeleri_cikar(self, images, tags=None, max_kelime=6):
        """Heuristic keyword extraction from sample-image generation
        prompts: keep only tokens that repeat across multiple sample
        prompts and aren't generic SD boilerplate OR generic character
        appearance (hair/eye color, hairstyle, expression, pose) - since
        these describe the character in the sample images, not the
        costume/outfit the LoRA actually controls. A candidate that
        also matches one of the model's own Civitai tags is kept even
        if it doesn't repeat often, since that's a strong extra signal
        that it's the actual subject of the LoRA rather than incidental
        prompt noise."""
        stopwords = {
            # quality / rendering boilerplate
            "masterpiece", "best quality", "high quality", "highres", "high resolution",
            "detailed", "extremely detailed", "intricate details", "ultra detailed",
            "4k", "8k", "absurdres", "sharp focus", "depth of field", "bokeh", "hdr",
            "cinematic lighting", "volumetric lighting", "natural lighting", "professional photography",
            "photorealistic", "hyperrealistic", "realistic", "perfect anatomy", "perfect hands",
            "trending on artstation", "art by", "detailed background", "official art", "8k wallpaper",
            "very aesthetic", "amazing quality", "newest", "anime coloring", "anime screencap",
            # generic subject count / composition
            "1girl", "1boy", "2girls", "2boys", "solo", "duo",
            "looking at viewer", "looking back", "looking away", "from side", "from behind",
            "from above", "from below", "cowboy shot", "upper body", "full body", "close-up",
            "dutch angle", "simple background", "white background", "grey background", "gray background",
            "black background", "indoors", "outdoors", "standing", "sitting", "kneeling", "squatting",
            # generic anatomy (not costume-specific)
            "medium breasts", "large breasts", "small breasts", "huge breasts", "breasts",
            "thighs", "midriff", "navel", "cleavage",
            # generic body type / build - describes the character's body, not the costume
            "petite", "curvy", "slim", "slender", "tall", "short", "chubby", "athletic",
            "skinny", "plump", "voluptuous", "muscular", "toned", "thick thighs",
            # generic expression / pose (character, not outfit)
            "smile", "light smile", "blush", "open mouth", "closed mouth", "closed eyes",
            # hairstyle shape (not accessories) - describes the character, not the costume
            "bangs", "blunt bangs", "hair between eyes", "hair over one eye", "ponytail",
            "twintails", "twin tails", "braid", "braided ponytail", "low ponytail", "high ponytail",
            "side ponytail", "drill hair", "ahoge", "sidelocks", "short hair", "long hair",
            "medium hair", "very long hair",
        }
        # Hair/eye colors: filtered by pattern rather than an exhaustive
        # list, since "<color> hair" / "<color> eyes" always describes
        # the character, never the costume.
        _hair_eye_pattern = re.compile(r"^(black|blonde|blond|brown|red|white|silver|grey|gray|pink|blue|purple|violet|green|orange|multicolored|two-tone|gradient|dark|light)\s+(hair|eyes)$")

        tekrar_sayaci = {}
        toplam_prompt = 0

        for img in images or []:
            meta = img.get("meta") or {}
            prompt = meta.get("prompt") or ""
            if not prompt:
                continue
            toplam_prompt += 1

            prompt = re.sub(r"<lora:[^>]+>", "", prompt, flags=re.IGNORECASE)
            gorulenler = set()
            for parca in prompt.split(","):
                token = parca.strip()
                token = re.sub(r"^\(+|\)+$", "", token)
                token = re.sub(r":\s*[\d.]+$", "", token).strip()
                if not token or len(token) < 3:
                    continue
                normalized = token.lower().replace("_", " ")
                if normalized in stopwords or _hair_eye_pattern.match(normalized):
                    continue
                key = normalized
                if key in gorulenler:
                    continue
                gorulenler.add(key)
                if key not in tekrar_sayaci:
                    tekrar_sayaci[key] = {"count": 0, "original": token}
                tekrar_sayaci[key]["count"] += 1

        if toplam_prompt == 0:
            return ""

        tags_lower = set()
        for tag in (tags or []):
            name = tag if isinstance(tag, str) else (tag.get("name") if isinstance(tag, dict) else None)
            if name:
                tags_lower.add(str(name).strip().lower())

        esik = max(2, (toplam_prompt // 2) + 1) if toplam_prompt > 1 else 1
        secilenler = [v["original"] for key, v in tekrar_sayaci.items() if v["count"] >= esik or key in tags_lower]
        return ", ".join(secilenler[:max_kelime])

    def _aciklamadan_trigger_cikar(self, description_html):
        """Some creators (e.g. taiarts) write the trigger word/phrase in
        the free-text model description instead of Civitai's dedicated
        trainedWords field. Look for an explicit 'trigger word(s):' /
        'activation text:' style line and use whatever follows it."""
        if not description_html:
            return ""
        metin = re.sub(r"<[^>]+>", " ", description_html)
        metin = html.unescape(metin)
        desenler = [
            r"trigger\s*words?\s*[:\-]\s*([^\n<.]{3,150})",
            r"activation\s*(?:text|words?|prompt)\s*[:\-]\s*([^\n<.]{3,150})",
            r"tetikleyici\s*kelime(?:ler)?\s*[:\-]\s*([^\n<.]{3,150})",
        ]
        for desen in desenler:
            eslesme = re.search(desen, metin, re.IGNORECASE)
            if eslesme:
                aday = eslesme.group(1).strip(" :\u2014\u2013-")
                if aday:
                    return aday
        return ""

    def _trigger_dosyalarini_guncelle(self, root, base_adi, trigger_metni):
        """Write the trigger words to both common conventions, without
        ever overwriting something that's already there:
        1) <base>.civitai.info -> "trainedWords" list (if the file exists)
        2) <base>.json -> "activation text" (the field A1111/Forge's
           built-in Lora card reads for 'Insert trigger words')."""
        info_path = os.path.join(root, base_adi + ".civitai.info")
        if os.path.exists(info_path):
            try:
                with open(info_path, "r", encoding="utf-8") as f:
                    veri = json.load(f)
                if not veri.get("trainedWords"):
                    veri["trainedWords"] = [w.strip() for w in trigger_metni.split(",") if w.strip()]
                    with open(info_path, "w", encoding="utf-8") as f:
                        json.dump(veri, f, indent=4, ensure_ascii=False)
            except Exception:
                pass

        json_path = os.path.join(root, base_adi + ".json")
        try:
            meta = {}
            if os.path.exists(json_path):
                with open(json_path, "r", encoding="utf-8") as f:
                    meta = json.load(f)
            if not meta.get("activation text"):
                meta["activation text"] = trigger_metni
                with open(json_path, "w", encoding="utf-8") as f:
                    json.dump(meta, f, indent=4, ensure_ascii=False)
        except Exception:
            pass

    def ana_motor_rename(self, mod, kaynak, hedef, config):
        self.islem_devam_ediyor = True
        self.istatistik_yeniden_adlandirilan = 0
        self.istatistik_trigger_dolduruldu = 0
        self.progress_bar.set(0)
        self.lbl_yuzde.configure(text="%0")
        self.lbl_durum.configure(text=f'{t("status_label_prefix", self.lang)} {t("status_running", self.lang)}')

        api = self.api_key.get()
        headers = {"Authorization": f"Bearer {api}"} if api else {}

        self.log_yaz(t("log_system_started", self.lang, mode="RENAME/TRIGGER"))

        islem_listesi = []
        for root, dirs, files in os.walk(kaynak):
            for file in files:
                if file.endswith((".safetensors", ".ckpt", ".pt")):
                    islem_listesi.append((root, file))

        toplam_model = len(islem_listesi)
        self.log_yaz(t("log_total_models", self.lang, count=toplam_model))

        for index, (root, file) in enumerate(islem_listesi):
            dosya_yolu = os.path.join(root, file)
            if not os.path.exists(dosya_yolu):
                continue

            base_adi = os.path.splitext(file)[0]
            self.log_yaz(t("log_model", self.lang, file=file))

            m_id, model_verisi, model_adi, trained_words, images, tags = None, None, None, [], [], []

            info_p = os.path.join(root, base_adi + ".civitai.info")
            if os.path.exists(info_p):
                try:
                    with open(info_p, "r", encoding="utf-8") as f:
                        j = json.load(f)
                        m_id = j.get("modelId") or j.get("id")
                        model_adi = (j.get("model") or {}).get("name")
                        trained_words = j.get("trainedWords") or []
                        images = j.get("images") or []
                        tags = j.get("tags") or []
                except Exception:
                    pass

            if not model_adi or (config["trigger"] and not trained_words and not images):
                try:
                    if m_id:
                        url = f"https://{API_DOMAIN}/api/v1/model-versions/{m_id}"
                    else:
                        url = f"https://{API_DOMAIN}/api/v1/model-versions/by-hash/{self.get_hash(dosya_yolu)}"
                    cevap = self.session.get(url, headers=headers, params=CIVITAI_CONTENT_PARAMS, timeout=10)
                    if cevap.status_code == 200:
                        model_verisi = cevap.json()
                        m_id = model_verisi.get("modelId")
                        model_adi = model_adi or (model_verisi.get("model") or {}).get("name")
                        trained_words = trained_words or model_verisi.get("trainedWords") or []
                        images = images or model_verisi.get("images") or []
                    else:
                        self.log_yaz(t("log_api_failed", self.lang))
                except Exception:
                    self.log_yaz(t("log_api_failed", self.lang))

            if not model_adi:
                self.log_yaz(t("log_no_metadata", self.lang))
            else:
                yeniden_ad_gerekli = (config["mode"] == "all" and self.dosya_temizle_adi(model_adi) != base_adi) or \
                                     (config["mode"] == "meaningless" and is_meaningless_name(base_adi))
                if yeniden_ad_gerekli:
                    yeni_base = self.dosya_temizle_adi(model_adi)
                    if yeni_base != base_adi:
                        sonuc = self.rename_related_files(root, base_adi, yeni_base, config["cakisma"])
                        if sonuc:
                            self.log_yaz(t("log_renamed_files", self.lang, old=base_adi, new=yeni_base))
                            self.istatistik_yeniden_adlandirilan += 1
                            base_adi = yeni_base
                elif config["mode"] == "meaningless":
                    self.log_yaz(t("log_rename_meaningless_skip", self.lang))

            if config["trigger"]:
                mevcut_trigger = "".join(trained_words) if trained_words else ""
                if not mevcut_trigger:
                    json_path = os.path.join(root, base_adi + ".json")
                    if os.path.exists(json_path):
                        try:
                            with open(json_path, "r", encoding="utf-8") as f:
                                mevcut_trigger = (json.load(f) or {}).get("activation text", "")
                        except Exception:
                            mevcut_trigger = ""

                if mevcut_trigger:
                    self.log_yaz(t("log_trigger_already", self.lang))
                elif trained_words:
                    kelimeler = ", ".join(trained_words)
                    self._trigger_dosyalarini_guncelle(root, base_adi, kelimeler)
                    self.log_yaz(t("log_trigger_from_api", self.lang, words=kelimeler))
                    self.istatistik_trigger_dolduruldu += 1
                else:
                    if not tags and m_id:
                        try:
                            r2 = self.session.get(f"https://{API_DOMAIN}/api/v1/models/{m_id}", headers=headers, params=CIVITAI_CONTENT_PARAMS, timeout=10)
                            if r2.status_code == 200:
                                model_ust_veri = r2.json()
                                tags = model_ust_veri.get("tags") or []
                                aciklama_metni = model_ust_veri.get("description", "")
                            else:
                                aciklama_metni = ""
                        except Exception:
                            aciklama_metni = ""
                    else:
                        aciklama_metni = ""

                    kelimeler = self._trigger_kelimeleri_cikar(images, tags=tags)
                    kaynak_aciklama = False
                    if not kelimeler and aciklama_metni:
                        kelimeler = self._aciklamadan_trigger_cikar(aciklama_metni)
                        kaynak_aciklama = bool(kelimeler)
                    if kelimeler:
                        self._trigger_dosyalarini_guncelle(root, base_adi, kelimeler)
                        if kaynak_aciklama:
                            self.log_yaz(t("log_trigger_from_description", self.lang, words=kelimeler))
                        else:
                            self.log_yaz(t("log_trigger_extracted", self.lang, words=kelimeler))
                        self.istatistik_trigger_dolduruldu += 1
                    else:
                        self.log_yaz(t("log_trigger_none_found", self.lang))

            ilerleme_orani = (index + 1) / toplam_model if toplam_model > 0 else 1
            self.progress_bar.set(ilerleme_orani)
            self.lbl_yuzde.configure(text=f"%{int(ilerleme_orani * 100)}")
            time.sleep(0.5)

        self._hash_cache_kaydet()

        ozet_metni = t(
            "summary_text_rename", self.lang,
            renamed=self.istatistik_yeniden_adlandirilan,
            triggers=self.istatistik_trigger_dolduruldu,
        )

        self.log_yaz(f'{t("log_summary_title", self.lang)}\n{ozet_metni}')
        self.lbl_durum.configure(text=f'{t("status_label_prefix", self.lang)} {t("status_done", self.lang)}')
        self.islem_devam_ediyor = False
        self.btn_cp.configure(state="normal")
        self.btn_lr.configure(state="normal")
        self.btn_tm.configure(state="normal")
        self.btn_rn.configure(state="normal")
        messagebox.showinfo(t("dialog_report_title", self.lang), ozet_metni)


if __name__ == "__main__":
    app = LoraLibrarianApp()
    app.mainloop()
